from routes.user import *
from routes.tenant import *
from routes.properties import *
from routes.contract import *
from routes.properties_type import *
from routes.rooms import *
from routes.maintenance import *
from routes.payments import *
from routes.reports import *
from routes.login import *
from routes.dashboard import *
from routes.print_payment import *
from routes.print_reports import *