"""edit tbl 

Revision ID: 017ebe70dbc2
Revises: 677a35a1571f
Create Date: 2025-12-11 22:52:48.464463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017ebe70dbc2'
down_revision = '677a35a1571f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.alter_column('property_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'property_types', ['type_id'], ['type_id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'owners', ['owner_id'], ['owner_id'])
        batch_op.alter_column('property_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
