"""add col status to room

Revision ID: 37630d4ac67c
Revises: eea6a3db1628
Create Date: 2025-12-12 03:55:19.092928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37630d4ac67c'
down_revision = 'eea6a3db1628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('rent_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('rent_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
