"""add new col to payments

Revision ID: 8a655cc80556
Revises: 37630d4ac67c
Create Date: 2025-12-13 01:13:49.060282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a655cc80556'
down_revision = '37630d4ac67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('remaining', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('remaining')
        batch_op.drop_column('total_paid')

    # ### end Alembic commands ###
