"""add tabel properties

Revision ID: eea6a3db1628
Revises: 017ebe70dbc2
Create Date: 2025-12-11 23:53:10.533085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea6a3db1628'
down_revision = '017ebe70dbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_properties_type_id', 'properties_type', ['type_id'], ['type_id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_properties_type_id', type_='foreignkey')
        batch_op.drop_column('type_id')

    op.drop_table('properties_type')
    # ### end Alembic commands ###
